version : "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  app:
    image: scheduling-node-app
    ports:
      - 13000:3000